#!/usr/bin/env python3
"""Build seed SQL + master CSV for the exercise library.

Reads:
  data/exercises.json              (free-exercise-db, public domain, 873 exercises)
  data/supplemental-exercises.json (original additions: HIIT/conditioning/mobility)
  data/yoga-stretch-exercises.json  (original: Bikram 26, other yoga, extra stretches)

Writes:
  seed_exercises.sql      INSERTs for body_part, equipment, exercise,
                          exercise_instruction, exercise_body_part,
                          exercise_equipment, exercise_metric
  data/master-exercise-list.csv   human-browsable combined index

Usage:
  python3 scripts/build_seed_sql.py
  psql -d exercise_app -f schema.sql -f seed_exercises.sql
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# free-exercise-db category -> exercise_modality enum
MODALITY = {
    "strength": "strength",
    "stretching": "stretching",
    "plyometrics": "plyometrics",
    "powerlifting": "powerlifting",
    "olympic weightlifting": "olympic_weightlifting",
    "strongman": "strongman",
    "cardio": "cardio",
    "hiit": "hiit",
    "mobility": "mobility",
    "yoga": "yoga",
}

LEVEL = {"beginner": "beginner", "intermediate": "intermediate",
         "advanced": "advanced", "expert": "expert"}

# region per muscle, used to seed the body_part tree
MUSCLE_REGION = {
    "abdominals": "core", "lower back": "core", "neck": "core",
    "chest": "upper", "shoulders": "upper", "traps": "upper", "lats": "upper",
    "middle back": "upper", "biceps": "upper", "triceps": "upper", "forearms": "upper",
    "quadriceps": "lower", "hamstrings": "lower", "glutes": "lower",
    "calves": "lower", "adductors": "lower", "abductors": "lower",
}

EQUIPMENT_CATEGORY = {
    "barbell": ("free_weights", True), "dumbbell": ("free_weights", True),
    "kettlebells": ("free_weights", True), "e-z curl bar": ("free_weights", True),
    "medicine ball": ("free_weights", True), "sandbag": ("free_weights", True),
    "cable": ("machine", True), "machine": ("machine", True),
    "sled": ("machine", True),
    "rowing machine": ("cardio", False), "air bike": ("cardio", False),
    "ski erg": ("cardio", False), "treadmill": ("cardio", False),
    "bands": ("accessory", False), "exercise ball": ("accessory", False),
    "foam roll": ("accessory", False), "battle ropes": ("accessory", False),
    "jump rope": ("accessory", False), "plyo box": ("accessory", False),
    "agility ladder": ("accessory", False), "suspension trainer": ("accessory", False),
    "body only": ("none", False), "other": ("none", False),
}

# default rest (seconds) by modality when the source has no explicit value
DEFAULT_REST = {
    "strength": 90, "powerlifting": 150, "olympic_weightlifting": 120,
    "strongman": 120, "plyometrics": 60, "cardio": 60, "hiit": 45,
    "stretching": 15, "mobility": 15, "yoga": 15,
}
MIN_REST = {
    "strength": 30, "powerlifting": 60, "olympic_weightlifting": 60,
    "strongman": 60, "plyometrics": 30, "cardio": 15, "hiit": 15,
    "stretching": 0, "mobility": 0, "yoga": 0,
}


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return re.sub(r"-{2,}", "-", s)


def q(text):
    """SQL-quote a string (or NULL)."""
    if text is None:
        return "NULL"
    return "'" + str(text).replace("'", "''") + "'"


def metrics_for(ex, modality: str, loadable: bool):
    """Pick the tracked metrics; first entry is primary."""
    if ex.get("force") == "static" or modality in ("stretching", "mobility", "yoga"):
        return ["duration"]
    if modality == "cardio":
        return ["duration", "distance", "calories"]
    if modality == "hiit":
        return ["reps", "duration"]
    if loadable:
        return ["reps", "weight"]
    return ["reps"]


def main():
    base = json.loads((ROOT / "data" / "exercises.json").read_text())
    extra = json.loads((ROOT / "data" / "supplemental-exercises.json").read_text())
    extra += json.loads((ROOT / "data" / "yoga-stretch-exercises.json").read_text())
    for ex in base:
        ex["_source"] = "free-exercise-db"
    for ex in extra:
        ex["_source"] = "original"
    combined = base + extra

    # dedupe by slug, keeping the first occurrence
    seen, exercises = set(), []
    for ex in combined:
        slug = slugify(ex["name"])
        if slug in seen:
            print(f"!! duplicate slug skipped: {slug} ({ex['_source']})")
            continue
        seen.add(slug)
        ex["_slug"] = slug
        exercises.append(ex)

    muscles = sorted({m for ex in exercises
                      for m in ex.get("primaryMuscles", []) + ex.get("secondaryMuscles", [])})
    equipment = sorted({ex["equipment"] for ex in exercises if ex.get("equipment")})

    out = ["-- Generated by scripts/build_seed_sql.py — do not edit by hand.",
           "BEGIN;", ""]

    out.append("-- body parts")
    for m in muscles:
        region = MUSCLE_REGION.get(m, "other")
        out.append(f"INSERT INTO body_part (slug, name, region) "
                   f"VALUES ({q(slugify(m))}, {q(m)}, {q(region)});")

    out.append("\n-- equipment")
    for e in equipment:
        cat, loadable = EQUIPMENT_CATEGORY.get(e, ("accessory", False))
        out.append(f"INSERT INTO equipment (slug, name, category, is_loadable) "
                   f"VALUES ({q(slugify(e))}, {q(e)}, {q(cat)}, {loadable});")

    out.append("\n-- exercises")
    for ex in exercises:
        modality = MODALITY[ex["category"]]
        level = LEVEL[ex["level"]]
        rest = ex.get("restSeconds", DEFAULT_REST[modality])
        min_rest = min(MIN_REST[modality], rest)
        loadable = bool(ex.get("equipment")) and \
            EQUIPMENT_CATEGORY.get(ex["equipment"], ("", False))[1]
        out.append(
            "INSERT INTO exercise (slug, name, modality, force, mechanic, level, "
            "min_rest_seconds, default_rest_seconds, source, source_id, status) VALUES ("
            f"{q(ex['_slug'])}, {q(ex['name'])}, {q(modality)}, "
            f"{q(ex.get('force'))}, {q(ex.get('mechanic'))}, {q(level)}, "
            f"{min_rest}, {rest}, {q(ex['_source'])}, {q(ex.get('id'))}, 'published');")

        for phase, steps in (("setup", ex.get("setup", [])),
                             ("execution", ex.get("instructions", []))):
            for i, step in enumerate(s for s in steps if s.strip()):
                out.append(
                    "INSERT INTO exercise_instruction (exercise_id, phase, step_number, body) "
                    f"SELECT id, {q(phase)}, {i + 1}, {q(step)} "
                    f"FROM exercise WHERE slug = {q(ex['_slug'])};")

        for role, key in (("primary", "primaryMuscles"), ("secondary", "secondaryMuscles")):
            for m in dict.fromkeys(ex.get(key, [])):  # de-dupe, keep order
                if role == "secondary" and m in ex.get("primaryMuscles", []):
                    continue
                out.append(
                    "INSERT INTO exercise_body_part (exercise_id, body_part_id, role) "
                    f"SELECT e.id, b.id, {q(role)} FROM exercise e, body_part b "
                    f"WHERE e.slug = {q(ex['_slug'])} AND b.slug = {q(slugify(m))};")

        if ex.get("equipment"):
            out.append(
                "INSERT INTO exercise_equipment (exercise_id, equipment_id, is_required) "
                f"SELECT e.id, q.id, true FROM exercise e, equipment q "
                f"WHERE e.slug = {q(ex['_slug'])} AND q.slug = {q(slugify(ex['equipment']))};")

        for i, metric in enumerate(metrics_for(ex, modality, loadable)):
            out.append(
                "INSERT INTO exercise_metric (exercise_id, metric, is_primary) "
                f"SELECT id, {q(metric)}, {i == 0} "
                f"FROM exercise WHERE slug = {q(ex['_slug'])};")

    out += ["", "COMMIT;", ""]
    (ROOT / "seed_exercises.sql").write_text("\n".join(out))
    print(f"seed_exercises.sql: {len(exercises)} exercises")

    with (ROOT / "data" / "master-exercise-list.csv").open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["slug", "name", "modality", "level", "force", "mechanic",
                    "equipment", "primary_muscles", "secondary_muscles",
                    "rest_seconds", "source"])
        for ex in sorted(exercises, key=lambda e: (MODALITY[e["category"]], e["_slug"])):
            modality = MODALITY[ex["category"]]
            w.writerow([
                ex["_slug"], ex["name"], modality, ex["level"],
                ex.get("force") or "", ex.get("mechanic") or "",
                ex.get("equipment") or "",
                "; ".join(ex.get("primaryMuscles", [])),
                "; ".join(ex.get("secondaryMuscles", [])),
                ex.get("restSeconds", DEFAULT_REST[modality]),
                ex["_source"],
            ])
    print("data/master-exercise-list.csv written")


if __name__ == "__main__":
    main()
