/**
 * ImageChef — OUT: Output Browser
 *
 * Shows run history. Each run can be expanded to browse its output image gallery.
 * Clicking an output image opens a before/after comparison in CMP.
 */

import { getAllRuns, deleteRun, getRun }       from '../data/runs.js';
import { getFolder, listImages,
         getOrCreateOutputSubfolder }          from '../data/folders.js';
import { saveShowcase }                        from '../data/showcases.js';
import { navigate }                            from '../main.js';
import { formatDateTime, formatBytes, uuid, now } from '../utils/misc.js';
import { showConfirm }                            from '../utils/dialogs.js';
import { getSettings }                            from '../utils/settings.js';
import { backfillRunThumbnails, THUMBNAIL_VERSION, getRunOutputFiles } from '../utils/run-thumbnail.js';
import { isVideoFile }                              from '../utils/video-frame.js';

function escHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function statusBadge(status) {
  const cfg = {
    completed: ['check_circle', 'ic-badge--green', 'Completed'],
    failed:    ['error',        'ic-badge--red',   'Failed'],
    cancelled: ['cancel',       '',                'Cancelled'],
    running:   ['sync',         'ic-badge--blue',  'Running'],
  }[status] || ['help', '', status];
  return `<span class="ic-badge ${cfg[1]}"><span class="material-symbols-outlined" style="font-size:11px">${cfg[0]}</span> ${cfg[2]}</span>`;
}

function durationStr(run) {
  if (!run.finishedAt || !run.startedAt) return '—';
  const ms = run.finishedAt - run.startedAt;
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms/1000).toFixed(1)}s`;
  return `${Math.floor(ms/60000)}m ${Math.round((ms%60000)/1000)}s`;
}

/**
 * Render the thumbnail slot for a run row.
 *  - If the run has a cached `thumbnail` data URL → render the image.
 *  - Otherwise render a placeholder (spinner for completed runs that are
 *    candidates for backfill, status icon for everything else).
 */
function thumbSlotHTML(run) {
  // Only trust thumbnails generated by the current selection logic.
  // Older cached values may have come from a sibling run sharing the
  // same output folder (see THUMBNAIL_VERSION in utils/run-thumbnail.js).
  if (run.thumbnail && run.thumbnailVersion === THUMBNAIL_VERSION) {
    return `<div class="out-run-thumb" data-thumb-id="${run.id}">
      <img class="out-run-thumb__img" src="${run.thumbnail}" alt="" loading="lazy" decoding="async">
    </div>`;
  }
  // Placeholder. Backfill step replaces innerHTML once the thumb is ready.
  const placeholderIcon = run.status === 'completed' ? 'image' :
                          run.status === 'running'   ? 'sync' :
                          run.status === 'failed'    ? 'error' :
                                                        'block';
  return `<div class="out-run-thumb out-run-thumb--placeholder" data-thumb-id="${run.id}">
    <span class="material-symbols-outlined">${placeholderIcon}</span>
  </div>`;
}

export async function render(container, hash) {
  const params       = new URLSearchParams((hash || '').split('?')[1] || '');
  const autoRunId    = params.get('run');
  const filterRecipe = params.get('recipe');
  container.innerHTML = `
    <div class="screen out-screen">
      <div class="screen-header">
        <div class="screen-title">
          <span class="material-symbols-outlined">history</span>
          Output History
        </div>
        <button class="btn-secondary" id="out-btn-clear-all">
          <span class="material-symbols-outlined">delete_sweep</span>
          Clear All
        </button>
      </div>
      <div class="out-filter-bar" id="out-filter-bar">
        <span class="material-symbols-outlined" style="font-size:18px;color:var(--ps-text-faint);flex-shrink:0">filter_list</span>
        <select id="out-filter-recipe" class="out-filter-select">
          <option value="">All recipes</option>
        </select>
        <span class="text-sm text-muted" style="flex-shrink:0">From</span>
        <input type="date" id="out-filter-from" class="out-filter-date" title="From date">
        <span class="text-sm text-muted" style="flex-shrink:0">to</span>
        <input type="date" id="out-filter-to" class="out-filter-date" title="To date">
        <button class="btn-secondary btn-sm" id="out-filter-clear" style="display:none">
          <span class="material-symbols-outlined" style="font-size:14px">close</span> Clear
        </button>
      </div>
      <div id="out-body" class="out-body">
        <div class="spinner spinner--lg" style="margin:40px auto;display:block"></div>
      </div>
    </div>

    <!-- Lightbox for single-image compare -->
    <div id="out-lightbox" class="out-lightbox" style="display:none">
      <div class="out-lightbox-bg" id="out-lb-bg"></div>
      <div class="out-lightbox-content" id="out-lb-content" style="padding:0;overflow:hidden">
        <!-- ImageWorkspace mounts here -->
      </div>
    </div>`;

  injectOutStyles();

  // ── Lightbox state ────────────────────────────────────────
  let currentPairs = [];
  let blobUrls = [];
  let fldWorkspace = null;

  async function ensureWorkspace() {
    if (fldWorkspace) return fldWorkspace;
    const { ImageWorkspace } = await import('../components/image-workspace.js');

    const wsDiv = document.createElement('div');
    wsDiv.style.position = 'absolute';
    wsDiv.style.inset = '0';
    container.querySelector('#out-lb-content').appendChild(wsDiv);

    fldWorkspace = new ImageWorkspace(wsDiv, {
      allowUpload: false,
      allowFolder: true, // Show carousel if multiple files
      customControlsHtml: `
        <button class="btn-secondary btn-sm iw-download-btn" title="Download output" style="margin-left:8px">
          <span class="material-symbols-outlined" style="font-size:14px">download</span>
        </button>
        <button class="btn-icon iw-close-btn" title="Close">
          <span class="material-symbols-outlined">close</span>
        </button>
      `,
      onBindCustomControls: (cnt) => {
        cnt.querySelector('.iw-close-btn')?.addEventListener('click', closeLightbox);
        cnt.querySelector('.iw-download-btn')?.addEventListener('click', () => {
          if (!fldWorkspace.activeFile) return;
          const a = document.createElement('a');
          a.href = URL.createObjectURL(fldWorkspace.activeFile);
          a.download = fldWorkspace.activeFile.name;
          a.click();
        });
      },
      onRender: async (file) => {
        const pair = currentPairs.find(p => p.outputFile === file);
        if (!pair) return null;

        const beforeUrl = URL.createObjectURL(pair.inputFile || pair.outputFile);
        const afterUrl = URL.createObjectURL(pair.outputFile);
        blobUrls.push(beforeUrl, afterUrl);

        return {
          beforeUrl,
          afterUrl,
          beforeLabel: pair.inputFile ? 'Input' : 'Output',
          afterLabel: pair.inputFile ? 'Output' : 'Output',
          context: { filename: file.name },
          canCompare: !!pair.inputFile
        };
      },
      onFilesChange: (files, activeFile) => {
        const titleEl = wsDiv.querySelector('.iw-title');
        if (titleEl && activeFile) {
          const idx = files.indexOf(activeFile) + 1;
          titleEl.textContent = `${activeFile.name}  (${idx}/${files.length})`;
        }
      }
    });

    return fldWorkspace;
  }

  async function openLightbox(pairs, startIdx) {
    // Image-only path. The image workspace can't render videos, so video
    // tiles are routed to openVideoLightbox instead (see thumb click
    // handler below).
    teardownVideoLightbox();
    currentPairs = pairs;
    container.querySelector('#out-lightbox').style.display = 'flex';
    container.querySelector('#out-lb-content').style.display = '';
    const ws = await ensureWorkspace();
    const files = pairs.map(p => p.outputFile);
    ws.setFiles(files, startIdx);
  }

  /**
   * Lightweight modal for video outputs. Reuses the existing lightbox
   * backdrop and content frame but mounts a native `<video controls>`
   * element instead of the image workspace, so video files actually play.
   * Includes a download affordance and a close button.
   */
  function openVideoLightbox(file) {
    teardownVideoLightbox();
    // Hide the image workspace content so it doesn't show through behind
    // the video pane.
    const lbContent = container.querySelector('#out-lb-content');
    if (lbContent) lbContent.style.display = 'none';

    const lb = container.querySelector('#out-lightbox');
    const url = URL.createObjectURL(file);
    blobUrls.push(url);

    const wrap = document.createElement('div');
    wrap.id = 'out-vlb-wrap';
    wrap.className = 'out-lightbox-content out-vlb';
    wrap.innerHTML = `
      <div class="out-vlb__bar">
        <span class="out-vlb__name" title="${escHtml(file.name)}">${escHtml(file.name)}</span>
        <button class="btn-secondary btn-sm out-vlb__download" title="Download">
          <span class="material-symbols-outlined" style="font-size:14px">download</span>
        </button>
        <button class="btn-icon out-vlb__close" title="Close">
          <span class="material-symbols-outlined">close</span>
        </button>
      </div>
      <div class="out-vlb__stage">
        <video class="out-vlb__video" src="${url}" controls autoplay playsinline></video>
      </div>
    `;
    lb.appendChild(wrap);
    lb.style.display = 'flex';

    wrap.querySelector('.out-vlb__close')?.addEventListener('click', closeLightbox);
    wrap.querySelector('.out-vlb__download')?.addEventListener('click', () => {
      const a = document.createElement('a');
      a.href = url;
      a.download = file.name;
      a.click();
    });
  }

  function teardownVideoLightbox() {
    const wrap = container.querySelector('#out-vlb-wrap');
    if (!wrap) return;
    // Pause the video before removing the node so playback actually stops
    // (some browsers keep audio playing if the element is detached mid-play).
    wrap.querySelector('video')?.pause();
    wrap.remove();
  }

  function closeLightbox() {
    container.querySelector('#out-lightbox').style.display = 'none';
    teardownVideoLightbox();
    const lbContent = container.querySelector('#out-lb-content');
    if (lbContent) lbContent.style.display = '';
    currentPairs = [];
    blobUrls.forEach(u => URL.revokeObjectURL(u));
    blobUrls = [];
  }

  container.querySelector('#out-lb-bg')?.addEventListener('click', closeLightbox);

  function handleKeydown(e) {
    if (container.querySelector('#out-lightbox').style.display === 'none') return;
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
      if (!fldWorkspace) return;
      const files = fldWorkspace.files;
      if (files.length <= 1) return;
      
      const idx = files.indexOf(fldWorkspace.activeFile);
      let newIdx = e.key === 'ArrowLeft' ? idx - 1 : idx + 1;
      if (newIdx < 0) newIdx = files.length - 1;
      if (newIdx >= files.length) newIdx = 0;
      
      fldWorkspace.setFiles(files, newIdx);
    }
  }
  document.addEventListener('keydown', handleKeydown);

  // ── Load runs ─────────────────────────────────────────────
  await loadRuns();

  async function loadRuns() {
    const body = container.querySelector('#out-body');
    if (!body) return;

    const runs = await getAllRuns();
    runs.sort((a, b) => (b.startedAt || 0) - (a.startedAt || 0));

    if (!runs.length) {
      body.innerHTML = `<div class="empty-state" style="padding-top:60px">
        <span class="material-symbols-outlined" style="font-size:48px">history</span>
        <div class="empty-state-title">No runs yet</div>
        <div class="empty-state-desc">Process a batch to see output history here.</div>
        <button class="btn-primary" id="out-go-lib">
          <span class="material-symbols-outlined">library_books</span> Browse Recipes
        </button>
      </div>`;
      body.querySelector('#out-go-lib')?.addEventListener('click', () => navigate('#lib'));
      return;
    }

    const completed = runs.filter(r => r.status === 'completed').length;
    const totalImgs = runs.reduce((s, r) => s + (r.successCount || 0), 0);

    body.innerHTML = `
      <div class="out-stats-bar">
        <div class="out-stat-card">
          <span class="out-stat-val">${runs.length}</span>
          <span class="out-stat-label">Total Runs</span>
        </div>
        <div class="out-stat-card">
          <span class="out-stat-val" style="color:var(--ps-green,#22c55e)">${completed}</span>
          <span class="out-stat-label">Completed</span>
        </div>
        <div class="out-stat-card">
          <span class="out-stat-val" style="color:var(--ps-blue)">${totalImgs}</span>
          <span class="out-stat-label">Images Processed</span>
        </div>
      </div>
      <div class="out-run-list">
        ${runs.map(run => runRowHTML(run)).join('')}
      </div>`;

    bindRunActions();
    initFilters(runs, container, { initialRecipeId: filterRecipe });

    // Lazily fill in any missing thumbnails. Each run's first output is
    // read from disk, scaled into a small JPEG, and persisted to its run
    // record so subsequent renders are instant. We update the DOM in
    // place as each thumbnail resolves.
    backfillRunThumbnails(runs, (run, dataUrl) => {
      const slot = container.querySelector(`.out-run-thumb[data-thumb-id="${run.id}"]`);
      if (!slot) return;
      if (!dataUrl) {
        // Generation failed/skipped — leave the placeholder where it is.
        slot.classList.add('out-run-thumb--unavailable');
        return;
      }
      slot.classList.remove('out-run-thumb--placeholder');
      slot.innerHTML = `<img class="out-run-thumb__img" src="${dataUrl}" alt="" loading="lazy" decoding="async">`;
    }).catch(err => console.warn('[out] thumbnail backfill failed', err));

    // Auto-open run from ?run= query param (e.g. navigated from QUE "View Results")
    if (autoRunId) {
      const targetRow = container.querySelector(`.out-run-row[data-id="${autoRunId}"]`);
      if (targetRow) {
        // Expand the detail panel and (for completed runs) trigger the
        // gallery loader directly — same behaviour as a row click.
        const detail = targetRow.querySelector(`#out-detail-${autoRunId}`);
        const icon   = targetRow.querySelector('.out-run-chevron');
        if (detail) detail.style.display = 'block';
        if (icon)   icon.style.transform = 'rotate(90deg)';
        if (targetRow.dataset.status === 'completed') {
          loadRunGallery(autoRunId, targetRow.dataset.subfolder || 'output');
        }
        targetRow.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }
  }

  function runRowHTML(run) {
    const thumbHTML = thumbSlotHTML(run);
    return `
      <div class="out-run-row" data-id="${run.id}" data-status="${run.status}" data-subfolder="${escHtml(run.outputFolder || 'output')}">
        <div class="out-run-header" data-expand-id="${run.id}">
          <span class="material-symbols-outlined out-run-chevron" style="font-size:16px;color:var(--ps-text-faint);transition:transform 200ms">chevron_right</span>
          ${thumbHTML}
          <div class="out-run-info">
            <div class="out-run-name">${escHtml(run.recipeName || 'Unknown Recipe')}</div>
            <div class="out-run-meta">
              <span class="mono text-sm text-muted">${run.outputFolder || '—'}</span>
              <span class="text-sm text-muted">${run.startedAt ? formatDateTime(run.startedAt) : '—'}</span>
            </div>
          </div>
          <div class="out-run-stats">
            ${statusBadge(run.status)}
            <span class="out-stat-inline"><span class="material-symbols-outlined" style="font-size:13px">image</span>${run.successCount ?? 0}/${run.imageCount ?? 0}</span>
            ${run.failCount ? `<span class="out-stat-inline" style="color:var(--ps-red)"><span class="material-symbols-outlined" style="font-size:13px">error</span>${run.failCount} failed</span>` : ''}
            <span class="out-stat-inline"><span class="material-symbols-outlined" style="font-size:13px">schedule</span>${durationStr(run)}</span>
          </div>
          <div class="out-run-actions">
            ${run.status === 'completed' ? `<button class="btn-secondary out-btn-browse" data-run-id="${run.id}" title="Browse in Folder Viewer" style="font-size:12px;padding:5px 10px">
              <span class="material-symbols-outlined" style="font-size:14px">folder_open</span>
              Browse
            </button>
            <button class="btn-icon out-btn-showcase" data-run-id="${run.id}" title="Add to ShowCase">
              <span class="material-symbols-outlined">star</span>
            </button>` : ''}
            <button class="btn-icon out-btn-edit" data-recipe-id="${run.recipeId}" title="Edit recipe">
              <span class="material-symbols-outlined">edit</span>
            </button>
            <button class="btn-icon out-btn-use" data-recipe-id="${run.recipeId}" title="Run batch again">
              <span class="material-symbols-outlined">play_arrow</span>
            </button>
            <button class="btn-icon out-btn-delete" data-id="${run.id}" title="Delete record">
              <span class="material-symbols-outlined" style="color:var(--ps-red)">delete</span>
            </button>
          </div>
        </div>

        <div class="out-run-detail" id="out-detail-${run.id}" style="display:none">
          <!-- Gallery section -->
          <div id="out-gallery-${run.id}" class="out-gallery-section" style="display:none"></div>
          <!-- Log section -->
          <div class="out-log-header">
            <span class="text-sm text-muted">Run log</span>
            <span class="mono text-sm text-muted">${run.id.slice(0,8)}</span>
          </div>
          <div class="terminal out-log-body">
            ${(run.log||[]).length === 0
              ? '<span style="color:var(--ps-text-faint)">No log entries.</span>'
              : (run.log||[]).map(e => {
                  const c = e.level === 'error' ? 'var(--ps-red)' : e.level === 'warn' ? '#f59e0b' : e.level === 'ok' ? '#22c55e' : e.level === 'info' ? 'var(--ps-text-muted)' : 'var(--ps-text-faint)';
                  return `<div><span style="color:var(--ps-text-faint)">[${new Date(e.ts).toLocaleTimeString()}]</span> <span style="color:${c}">[${e.level}]</span> <span style="color:${c === 'var(--ps-text-muted)' ? 'var(--ps-text)' : c}">${escHtml(e.msg)}</span></div>`;
                }).join('')}
          </div>
        </div>
      </div>`;
  }

  function bindRunActions() {
    // Row click → expand/collapse the detail panel. For completed runs,
    // first-time expansion also lazy-loads the output gallery so the user
    // sees both the run log AND the actual outputs in one click.
    container.querySelectorAll('[data-expand-id]').forEach(header => {
      header.addEventListener('click', e => {
        if (e.target.closest('button')) return;
        const id     = header.dataset.expandId;
        const detail = container.querySelector(`#out-detail-${id}`);
        const icon   = header.querySelector('.out-run-chevron');
        if (!detail) return;
        const open = detail.style.display !== 'none';
        detail.style.display = open ? 'none' : 'block';
        if (icon) icon.style.transform = open ? '' : 'rotate(90deg)';

        // On open: load the gallery once. Status is read from the row's
        // dataset rather than re-querying because the row has already been
        // rendered with the full status at this point.
        if (!open) {
          const row = header.closest('.out-run-row');
          const status = row?.dataset.status;
          if (status === 'completed') {
            const subfolder = row?.dataset.subfolder || 'output';
            loadRunGallery(id, subfolder);
          }
        }
      });
    });

    // Buttons inside the row header (Browse / Edit / Run again / ShowCase /
    // Delete) — bound here so they live alongside the row's lifecycle.
    bindRowSecondaryActions();
  }

  /**
   * Lazy-load and render the per-run output gallery into its slot inside
   * the detail panel. Idempotent — once loaded, subsequent calls are a
   * no-op (the slot is left visible inside the detail panel; the panel
   * itself controls overall visibility via the row click handler).
   */
  async function loadRunGallery(runId, subfolder) {
    const galleryEl = container.querySelector(`#out-gallery-${runId}`);
    if (!galleryEl) return;
    if (galleryEl.dataset.loaded === '1') {
      galleryEl.style.display = 'block';
      return;
    }

    galleryEl.style.display = 'block';
    galleryEl.innerHTML = `<div style="padding:12px;display:flex;align-items:center;gap:8px"><div class="spinner"></div><span class="text-sm text-muted">Loading output files…</span></div>`;

    try {
      const run = await getRun(runId);
      let outputHandle = run?.outputHandleObj || await getFolder('output');

      if (!outputHandle) {
        galleryEl.innerHTML = `<div class="out-gallery-empty">Output folder not accessible. <button class="btn-secondary out-btn-repick">Pick Folder</button></div>`;
        return;
      }

      let subHandle;
      try {
        subHandle = await getOrCreateOutputSubfolder(outputHandle, subfolder);
      } catch {
        galleryEl.innerHTML = `<div class="out-gallery-empty">Subfolder "${subfolder}" not found.</div>`;
        return;
      }

      // Resolve only this run's outputs (manifest-first, mtime-fallback
      // for legacy runs). Includes video files alongside images so
      // video-producing recipes show their results too.
      const outputFiles = await getRunOutputFiles(run);
      if (!outputFiles.length) {
        galleryEl.innerHTML = `<div class="out-gallery-empty">No output files found for this run.</div>`;
        return;
      }

          // Try to find matching input files for the before/after compare
          // affordance. Inputs are images only — videos are output-only.
          const inputHandle = await getFolder('input');
          let inputFiles = [];
          if (inputHandle) {
            try { inputFiles = await listImages(inputHandle, { includeVideo: true }); } catch {}
          }

          const inputByBaseName = new Map();
          for (const f of inputFiles) {
            const base = f.name.replace(/\.[^.]+$/, '').replace(/_\w+$/, ''); // strip suffix
            inputByBaseName.set(base, f);
            inputByBaseName.set(f.name.replace(/\.[^.]+$/, ''), f);
          }

          // Build image pairs — try progressively looser name matches
          const pairs = outputFiles.map(outFile => {
            const withoutExt    = outFile.name.replace(/\.[^.]+$/, '');         // "a_bw.jpg" → "a_bw"
            const withoutSuffix = withoutExt.replace(/[-_][a-z0-9]+$/i, '');    // "a_bw"    → "a"
            const withoutBoth   = withoutSuffix.replace(/\.[^.]+$/, '');        // "a.jpg"   → "a"
            const inFile = inputByBaseName.get(withoutExt)
                        || inputByBaseName.get(withoutSuffix)
                        || inputByBaseName.get(withoutBoth)
                        || null;
            return { outputFile: outFile, inputFile: inFile };
          });

          // Render gallery — videos use a <video> element with metadata
          // preload (browser shows the first frame as poster), images use
          // a plain <img>. A play badge sits in the corner of video tiles
          // so they're identifiable at a glance.
          const thumbs = pairs.map((pair, i) => {
            const url = URL.createObjectURL(pair.outputFile);
            const isVideo = isVideoFile(pair.outputFile);
            const media = isVideo
              ? `<video src="${url}" class="out-thumb-img" muted playsinline preload="metadata"></video>
                 <span class="out-thumb-badge" title="Video"><span class="material-symbols-outlined">play_circle</span></span>`
              : `<img src="${url}" class="out-thumb-img" draggable="false" loading="lazy">`;
            return `<div class="out-thumb${isVideo ? ' out-thumb--video' : ''}" data-pair-idx="${i}">
              ${media}
              <div class="out-thumb-overlay">
                <span class="out-thumb-name">${escHtml(pair.outputFile.name)}</span>
                <div class="out-thumb-btns">
                  ${pair.inputFile && !isVideo ? `<button class="btn-icon out-thumb-compare" data-pair-idx="${i}" title="Compare">
                    <span class="material-symbols-outlined" style="font-size:14px">compare</span>
                  </button>` : ''}
                  <button class="btn-icon out-thumb-download" data-pair-idx="${i}" title="Download">
                    <span class="material-symbols-outlined" style="font-size:14px">download</span>
                  </button>
                </div>
              </div>
            </div>`;
          }).join('');

          const matchCount = pairs.filter(p => p.inputFile).length;
          galleryEl.innerHTML = `
            <div class="out-gallery-header">
              <span class="text-sm text-muted">${outputFiles.length} file${outputFiles.length !== 1 ? 's' : ''} in <code>${subfolder}/</code></span>
              <button class="btn-secondary out-btn-browse-gallery" data-run-id="${runId}" style="font-size:11px;padding:4px 8px;margin-left:8px">
                <span class="material-symbols-outlined" style="font-size:13px">folder_open</span> Browse Folder
              </button>
              <button class="btn-secondary out-btn-showcase-gallery" data-run-id="${runId}" style="font-size:11px;padding:4px 8px;margin-left:4px">
                <span class="material-symbols-outlined" style="font-size:13px">star</span> Add to ShowCase
              </button>
              ${matchCount
                ? `<span class="text-sm text-muted" style="margin-left:6px">&nbsp;·&nbsp; ${matchCount} originals matched for comparison</span>`
                : `<span style="margin-left:8px;display:flex;align-items:center;gap:6px">
                     <span class="ic-badge">No originals matched</span>
                     <button class="btn-secondary out-btn-reload-gallery" data-run-id="${runId}" style="font-size:11px;padding:4px 8px">
                       <span class="material-symbols-outlined" style="font-size:13px">folder_open</span>
                       Re-authorize input folder
                     </button>
                   </span>`}
            </div>
            <div class="out-thumb-grid">${thumbs}</div>`;

          galleryEl.dataset.loaded = matchCount > 0 ? '1' : '0'; // allow reload if no originals matched

          // Browse folder button in gallery header
          galleryEl.querySelectorAll('.out-btn-browse-gallery').forEach(browseBtn => {
            browseBtn.addEventListener('click', e => {
              e.stopPropagation();
              navigate(`#fld?run=${browseBtn.dataset.runId}&from=out`);
            });
          });

          // Add to ShowCase button in gallery header
          galleryEl.querySelectorAll('.out-btn-showcase-gallery').forEach(shcBtn => {
            shcBtn.addEventListener('click', async e => {
              e.stopPropagation();
              const r = await getRun(shcBtn.dataset.runId);
              if (r) await addRunToShowcase(r, outputFiles);
            });
          });

          // Re-authorize input folder button — re-runs the gallery load
          // after the user grants permission so original-pair matching can
          // succeed.
          galleryEl.querySelectorAll('.out-btn-reload-gallery').forEach(reloadBtn => {
            reloadBtn.addEventListener('click', async e => {
              e.stopPropagation();
              try {
                await import('../data/folders.js').then(m => m.pickFolder('input'));
                galleryEl.dataset.loaded = '0'; // force reload
                loadRunGallery(runId, subfolder);
              } catch {}
            });
          });

          // Bind click handlers — route video tiles to the native video
          // player; everything else goes to the image-comparison workspace.
          galleryEl.querySelectorAll('.out-thumb').forEach(thumb => {
            thumb.addEventListener('click', e => {
              if (e.target.closest('button')) return;
              const idx = parseInt(thumb.dataset.pairIdx);
              const pair = pairs[idx];
              if (pair && isVideoFile(pair.outputFile)) {
                openVideoLightbox(pair.outputFile);
              } else {
                openLightbox(pairs, idx);
              }
            });
          });
          galleryEl.querySelectorAll('.out-thumb-compare').forEach(btn => {
            btn.addEventListener('click', e => {
              e.stopPropagation();
              openLightbox(pairs, parseInt(btn.dataset.pairIdx));
            });
          });
          galleryEl.querySelectorAll('.out-thumb-download').forEach(btn => {
            btn.addEventListener('click', e => {
              e.stopPropagation();
              const pair = pairs[parseInt(btn.dataset.pairIdx)];
              const a = document.createElement('a');
              a.href = URL.createObjectURL(pair.outputFile);
              a.download = pair.outputFile.name;
              a.click();
            });
          });

    } catch (err) {
      galleryEl.innerHTML = `<div class="out-gallery-empty">Error: ${escHtml(err.message)}</div>`;
    }
  }

  function bindRowSecondaryActions() {
    // Browse folder viewer
    container.querySelectorAll('.out-btn-browse').forEach(btn => {
      btn.addEventListener('click', e => {
        e.stopPropagation();
        navigate(`#fld?run=${btn.dataset.runId}&from=out`);
      });
    });

    // Edit recipe
    container.querySelectorAll('.out-btn-edit').forEach(btn => {
      btn.addEventListener('click', e => {
        e.stopPropagation();
        navigate(btn.dataset.recipeId ? `#bld?id=${btn.dataset.recipeId}` : '#lib');
      });
    });

    // Use recipe (run batch again)
    container.querySelectorAll('.out-btn-use').forEach(btn => {
      btn.addEventListener('click', e => {
        e.stopPropagation();
        navigate(btn.dataset.recipeId ? `#set?recipe=${btn.dataset.recipeId}` : '#lib');
      });
    });

    // Add to ShowCase (from run row)
    container.querySelectorAll('.out-btn-showcase').forEach(btn => {
      btn.addEventListener('click', async e => {
        e.stopPropagation();
        const run = await getRun(btn.dataset.runId);
        if (run) await addRunToShowcase(run);
      });
    });

    // Delete run
    container.querySelectorAll('.out-btn-delete').forEach(btn => {
      btn.addEventListener('click', async e => {
        e.stopPropagation();
        const confirmed = await showConfirm({
          title: 'Delete Run Record?',
          body: 'This will remove the execution record and its history. This action cannot be undone.',
          confirmText: 'Delete',
          variant: 'danger',
          icon: 'delete_forever'
        });
        if (!confirmed) return;
        await deleteRun(btn.dataset.id);
        await loadRuns();
      });
    });
  }

  // Clear all
  container.querySelector('#out-btn-clear-all')?.addEventListener('click', async () => {
    const runs = await getAllRuns();
    if (!runs.length) return;
    const confirmed = await showConfirm({
      title: 'Clear All History?',
      body: `Are you sure you want to delete all ${runs.length} execution records? This cannot be undone.`,
      confirmText: 'Clear All',
      variant: 'danger',
      icon: 'delete_sweep'
    });
    if (!confirmed) return;
    await Promise.all(runs.map(r => deleteRun(r.id)));
    window.AuroraToast?.show({ variant: 'success', title: 'All run records cleared' });
    await loadRuns();
  });

  return () => document.removeEventListener('keydown', handleKeydown);
}

// ── Filter bar ────────────────────────────────────────────────────────────────
function initFilters(runs, container, { initialRecipeId } = {}) {
  const recipeSelect = container.querySelector('#out-filter-recipe');
  const fromInput    = container.querySelector('#out-filter-from');
  const toInput      = container.querySelector('#out-filter-to');
  const clearBtn     = container.querySelector('#out-filter-clear');
  if (!recipeSelect) return;

  // Populate one option per unique recipe id. Value is the id (so the URL
  // ?recipe=<id> filter works and renames don't break things), label is
  // the recipe name. Sorted by display name for the user.
  const seen = new Map(); // recipeId → recipeName
  for (const r of runs) {
    if (!r.recipeId) continue;
    if (!seen.has(r.recipeId)) seen.set(r.recipeId, r.recipeName || '(unnamed recipe)');
  }
  [...seen.entries()]
    .sort((a, b) => a[1].localeCompare(b[1]))
    .forEach(([id, name]) => {
      const opt = document.createElement('option');
      opt.value = id;
      opt.textContent = name;
      recipeSelect.appendChild(opt);
    });

  function isFiltered() {
    return recipeSelect.value || fromInput.value || toInput.value;
  }

  function applyFilters() {
    const recipeId = recipeSelect.value;
    const fromMs   = fromInput.value ? new Date(fromInput.value).setHours(0,0,0,0)   : null;
    const toMs     = toInput.value   ? new Date(toInput.value).setHours(23,59,59,999) : null;

    container.querySelectorAll('.out-run-row').forEach(row => {
      const run = runs.find(r => r.id === row.dataset.id);
      if (!run) return;
      const recipeMatch = !recipeId || run.recipeId === recipeId;
      const fromMatch   = !fromMs   || (run.startedAt || 0) >= fromMs;
      const toMatch     = !toMs     || (run.startedAt || 0) <= toMs;
      row.style.display = (recipeMatch && fromMatch && toMatch) ? '' : 'none';
    });

    clearBtn.style.display = isFiltered() ? '' : 'none';
  }

  recipeSelect.addEventListener('change', applyFilters);
  fromInput.addEventListener('change', applyFilters);
  toInput.addEventListener('change', applyFilters);

  clearBtn.addEventListener('click', () => {
    recipeSelect.value = '';
    fromInput.value    = '';
    toInput.value      = '';
    applyFilters();
  });

  // Pre-apply the recipe filter from the URL — drives the "View recent
  // runs" link in the recipe Batch Setup sidebar.
  if (initialRecipeId && seen.has(initialRecipeId)) {
    recipeSelect.value = initialRecipeId;
    applyFilters();
  }
}

// ── Add to ShowCase helper ────────────────────────────────────────────────────
async function addRunToShowcase(run, preloadedFiles) {
  try {
    let files = preloadedFiles;
    if (!files) {
      let outputHandle = run.outputHandleObj || await getFolder('output');
      if (!outputHandle) {
        window.AuroraToast?.show({ variant: 'warning', title: 'Output folder not accessible' });
        return;
      }
      const subHandle = await getOrCreateOutputSubfolder(outputHandle, run.outputFolder || 'output');
      files = await listImages(subHandle, { includeVideo: true });
    }

    const sampleFiles     = files.slice(0, 5);
    const sampleFileNames = sampleFiles.map(f => f.name);

    // Capture matching input filenames so the showcase can show before/after
    let sampleInputFileNames = [];
    try {
      const inputHandle = await getFolder('input');
      if (inputHandle) {
        const inputFiles = await listImages(inputHandle, { includeVideo: true });
        const inputByBase = new Map();
        for (const f of inputFiles) {
          inputByBase.set(f.name.replace(/\.[^.]+$/, ''), f.name);
          inputByBase.set(f.name, f.name);
        }
        // Try 1:1 match for each output filename
        sampleInputFileNames = sampleFiles.map(outFile => {
          const base     = outFile.name.replace(/\.[^.]+$/, '');
          const stripped = base.replace(/[-_][a-z0-9]+$/i, '');
          return inputByBase.get(base) || inputByBase.get(stripped) || null;
        }).filter(Boolean);
        // Fallback: take the first 5 inputs when no name matches found
        if (!sampleInputFileNames.length && inputFiles.length) {
          sampleInputFileNames = inputFiles.slice(0, 5).map(f => f.name);
        }
      }
    } catch {}

    const entry = {
      id:                   uuid(),
      runId:                run.id,
      recipeId:             run.recipeId,
      recipeName:           run.recipeName,
      title:                run.recipeName,
      description:          '',
      sampleFileNames,
      sampleInputFileNames,
      createdAt:            now(),
      updatedAt:            now(),
    };
    await saveShowcase(entry);

    window.AuroraToast?.show({
      variant: 'success',
      title: 'Added to ShowCase',
      description: `<a href="#shc?id=${entry.id}" style="color:var(--ps-blue)">View entry →</a>`,
    });
  } catch (err) {
    console.error('[addRunToShowcase]', err);
    window.AuroraToast?.show({ variant: 'danger', title: 'Failed to add to ShowCase', description: err.message });
  }
}

let _outStyles = false;
function injectOutStyles() {
  if (_outStyles) return;
  _outStyles = true;
  const s = document.createElement('style');
  s.textContent = `
    .out-screen { display:flex; flex-direction:column; height:100%; }
    .out-filter-bar { display:flex; align-items:center; gap:8px; padding:6px 20px; border-bottom:1px solid var(--ps-border); flex-wrap:nowrap; overflow-x:auto; }
    .out-filter-select { padding:5px 8px; background:var(--ps-bg-surface); border:1px solid var(--ps-border); border-radius:7px; color:var(--ps-text); font-size:13px; cursor:pointer; max-width:200px; flex-shrink:0; }
    .out-filter-date { padding:5px 8px; background:var(--ps-bg-surface); border:1px solid var(--ps-border); border-radius:7px; color:var(--ps-text); font-size:13px; width:140px; flex-shrink:0; }
    .out-filter-select:focus, .out-filter-date:focus { outline:none; border-color:var(--ps-blue); }
    .out-body { flex:1; overflow-y:auto; padding:16px 20px; }

    .out-stats-bar { display:flex; gap:12px; margin-bottom:20px; }
    .out-stat-card { flex:1; background:var(--ps-bg-surface); border:1px solid var(--ps-border); border-radius:10px; padding:14px 16px; display:flex; flex-direction:column; gap:4px; }
    .out-stat-val { font-size:24px; font-weight:700; font-family:var(--font-mono); }
    .out-stat-label { font-size:11px; text-transform:uppercase; letter-spacing:.05em; color:var(--ps-text-faint); }

    .out-run-list { display:flex; flex-direction:column; gap:8px; }
    .out-run-row { background:var(--ps-bg-surface); border:1px solid var(--ps-border); border-radius:10px; overflow:hidden; }
    .out-run-header { display:flex; align-items:center; gap:10px; padding:12px 14px; cursor:pointer; transition:background 100ms; }
    .out-run-header:hover { background:var(--ps-bg-hover); }

    /* Run thumbnail (left of the row info). 16:10 cover-crop matches the
       JPEG written by ensureRunThumbnail(). */
    .out-run-thumb {
      flex-shrink: 0;
      width: 64px; height: 40px;
      border-radius: 6px;
      overflow: hidden;
      background: var(--ps-bg-app);
      border: 1px solid var(--ps-border);
      display: flex; align-items: center; justify-content: center;
      color: var(--ps-text-faint);
    }
    .out-run-thumb__img { width: 100%; height: 100%; object-fit: cover; display: block; }
    .out-run-thumb--placeholder .material-symbols-outlined { font-size: 20px; opacity: 0.55; }
    .out-run-thumb--unavailable { opacity: 0.6; }

    .out-run-info { flex:1; overflow:hidden; }
    .out-run-name { font-size:14px; font-weight:600; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; margin-bottom:3px; }
    .out-run-meta { display:flex; gap:12px; flex-wrap:wrap; }
    .out-run-stats { display:flex; align-items:center; gap:8px; flex-shrink:0; flex-wrap:wrap; }
    .out-run-actions { display:flex; gap:4px; flex-shrink:0; align-items:center; }
    .out-stat-inline { display:flex; align-items:center; gap:3px; font-size:12px; color:var(--ps-text-muted); font-family:var(--font-mono); }

    .out-run-detail { border-top:1px solid var(--ps-border); }
    .out-log-header { display:flex; justify-content:space-between; padding:8px 14px; background:var(--ps-bg-app); }
    .out-log-body { max-height:160px; overflow-y:auto; margin:0; border-radius:0; border:none; font-size:11px; line-height:1.6; }

    /* Gallery */
    .out-gallery-section { border-bottom:1px solid var(--ps-border); background:var(--ps-bg-app); padding:12px 14px; }
    .out-gallery-header { display:flex; align-items:center; margin-bottom:10px; flex-wrap:wrap; gap:4px; }
    .out-gallery-empty { padding:16px; color:var(--ps-text-muted); font-size:13px; }
    .out-thumb-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(120px,1fr)); gap:8px; }
    .out-thumb { position:relative; border-radius:8px; overflow:hidden; cursor:pointer; aspect-ratio:1; background:var(--ps-bg-surface); border:1px solid var(--ps-border); }
    .out-thumb:hover .out-thumb-overlay { opacity:1; }
    .out-thumb-img { width:100%; height:100%; object-fit:cover; display:block; }
    .out-thumb-badge {
      position:absolute; top:6px; right:6px;
      width:24px; height:24px; border-radius:50%;
      background:rgba(0,0,0,0.65); backdrop-filter:blur(4px);
      display:flex; align-items:center; justify-content:center;
      color:#fff; pointer-events:none;
    }
    .out-thumb-badge .material-symbols-outlined { font-size:18px; }
    .out-thumb-overlay { position:absolute; inset:0; background:rgba(0,0,0,0.65); display:flex; flex-direction:column; justify-content:flex-end; padding:6px; opacity:0; transition:opacity 150ms; }
    .out-thumb-name { font-size:9px; color:#fff; font-family:var(--font-mono); overflow:hidden; text-overflow:ellipsis; white-space:nowrap; margin-bottom:4px; }
    .out-thumb-btns { display:flex; gap:3px; }
    .out-thumb-btns .btn-icon { width:24px; height:24px; background:rgba(255,255,255,0.15); border-radius:4px; }
    .out-thumb-btns .btn-icon:hover { background:var(--ps-blue); }

    /* Lightbox */
    .out-lightbox { position:fixed; inset:0; z-index:500; display:flex; align-items:center; justify-content:center; }
    .out-lightbox-bg { position:absolute; inset:0; background:rgba(0,0,0,0.85); }
    .out-lightbox-content { position:relative; z-index:1; width:92vw; height:90vh; background:var(--ps-bg-surface); border:1px solid var(--ps-border); border-radius:14px; display:flex; flex-direction:column; overflow:hidden; box-shadow:0 24px 80px rgba(0,0,0,0.6); }

    /* Video lightbox — separate from the image workspace path. Reuses the
       same backdrop and frame size, but mounts a native <video> element. */
    .out-vlb { padding:0; }
    .out-vlb__bar {
      display:flex; align-items:center; gap:8px;
      padding:10px 14px; border-bottom:1px solid var(--ps-border);
      background:var(--ps-bg-app);
      flex-shrink:0;
    }
    .out-vlb__name {
      flex:1; min-width:0;
      font-size:13px; font-weight:500;
      color:var(--ps-text);
      font-family:var(--font-mono);
      overflow:hidden; text-overflow:ellipsis; white-space:nowrap;
    }
    .out-vlb__stage {
      flex:1; min-height:0;
      background:#000;
      display:flex; align-items:center; justify-content:center;
    }
    .out-vlb__video { width:100%; height:100%; object-fit:contain; display:block; }

  `;
  document.head.appendChild(s);
}
